'use client'

import { useState } from 'react'
import { toast } from 'sonner'
import { createClient } from '@/lib/supabase/client'
import {
  Dialog, DialogContent, DialogHeader,
  DialogTitle, DialogDescription,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Loader2, BookOpen } from 'lucide-react'

interface CreateRoomDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  userId: string
  onSuccess: () => void
}

export function CreateRoomDialog({ open, onOpenChange, userId, onSuccess }: CreateRoomDialogProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const supabase = createClient()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    const fd = new FormData(e.currentTarget)
    const name = (fd.get('name') as string).trim()
    const subject = (fd.get('subject') as string).trim()
    const description = (fd.get('description') as string).trim()

    try {
      // 1. Create room — invite_code auto-generated by DB
      const { data: room, error: roomErr } = await supabase
        .from('rooms')
        .insert({ name, subject, description: description || null, created_by: userId })
        .select('id')
        .single()

      if (roomErr) {
        console.error('Supabase Error creating room:', roomErr)
        throw roomErr
      }

      // 2. Add creator as owner
      const { error: memberErr } = await supabase
        .from('room_members')
        .insert({ room_id: room.id, user_id: userId, role: 'owner' })

      if (memberErr) {
        console.error('Supabase Error adding creator to room members:', memberErr)
        throw memberErr
      }

      // 3. Activity log
      const { error: logErr } = await supabase.from('activity_log').insert({
        room_id: room.id,
        user_id: userId,
        action: 'room_created',
      })

      if (logErr) {
        console.error('Supabase Error logging activity:', logErr)
        // Don't throw for log errors as the room is already created successfully
      }

      onOpenChange(false)
      ;(e.target as HTMLFormElement).reset()
      onSuccess()
    } catch (err: any) {
      console.error('Error in handleSubmit:', err)
      const msg = err.message || 'Failed to create room'
      setError(msg)
      toast.error(msg)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-zinc-900 border-zinc-800 text-white sm:max-w-md">
        <DialogHeader>
          <div className="flex items-center gap-2.5 mb-1">
            <div className="w-8 h-8 rounded-lg bg-violet-600/20 border border-violet-500/30 flex items-center justify-center">
              <BookOpen className="w-4 h-4 text-violet-400" />
            </div>
            <DialogTitle className="text-white text-lg">Create Study Room</DialogTitle>
          </div>
          <DialogDescription className="text-zinc-400 text-sm">
            An 8-character invite code will be auto-generated for your room.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 mt-1">
          {error && (
            <div className="rounded-lg bg-red-950/50 border border-red-900/50 px-3.5 py-2.5 text-sm text-red-400">
              {error}
            </div>
          )}

          <div className="space-y-1.5">
            <Label htmlFor="create-name" className="text-zinc-300 text-sm font-medium">
              Room Name <span className="text-red-400">*</span>
            </Label>
            <Input
              id="create-name"
              name="name"
              placeholder="e.g. UPSC 2025 Prep"
              maxLength={50}
              required
              disabled={loading}
              className="bg-zinc-800/60 border-zinc-700 text-white placeholder:text-zinc-500 focus-visible:ring-violet-500/50 focus-visible:border-violet-500/50 h-10"
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="create-subject" className="text-zinc-300 text-sm font-medium">
              Subject / Topic <span className="text-red-400">*</span>
            </Label>
            <Input
              id="create-subject"
              name="subject"
              placeholder="e.g. Mathematics, DSA, Chemistry"
              required
              disabled={loading}
              className="bg-zinc-800/60 border-zinc-700 text-white placeholder:text-zinc-500 focus-visible:ring-violet-500/50 focus-visible:border-violet-500/50 h-10"
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="create-description" className="text-zinc-300 text-sm font-medium">
              Description{' '}
              <span className="text-zinc-600 font-normal">(optional, max 200 chars)</span>
            </Label>
            <Textarea
              id="create-description"
              name="description"
              placeholder="What topics will you cover in this room?"
              maxLength={200}
              rows={3}
              disabled={loading}
              className="bg-zinc-800/60 border-zinc-700 text-white placeholder:text-zinc-500 focus-visible:ring-violet-500/50 focus-visible:border-violet-500/50 resize-none"
            />
          </div>

          <div className="flex justify-end gap-2.5 pt-2 border-t border-zinc-800">
            <Button
              type="button"
              variant="ghost"
              onClick={() => onOpenChange(false)}
              disabled={loading}
              className="text-zinc-400 hover:text-white hover:bg-zinc-800"
            >
              Cancel
            </Button>
            <Button
              id="create-room-submit"
              type="submit"
              disabled={loading}
              className="bg-violet-600 hover:bg-violet-500 text-white min-w-28 shadow-lg shadow-violet-900/20"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Creating…
                </>
              ) : (
                'Create Room'
              )}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}
