'use client'

import { useState } from 'react'
import { toast } from 'sonner'
import { createClient } from '@/lib/supabase/client'
import {
  Dialog, DialogContent, DialogHeader,
  DialogTitle, DialogDescription,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Loader2, BookOpen } from 'lucide-react'

interface CreateRoomDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  userId: string
  onSuccess: () => void
}

export function CreateRoomDialog({ open, onOpenChange, userId, onSuccess }: CreateRoomDialogProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const supabase = createClient()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    const fd = new FormData(e.currentTarget)
    const name = (fd.get('name') as string).trim()
    const subject = (fd.get('subject') as string).trim()
    const description = (fd.get('description') as string).trim()

    try {
      // 1. Create room — invite_code auto-generated by DB
      const { data: room, error: roomErr } = await supabase
        .from('rooms')
        .insert({ name, subject, description: description || null, created_by: userId })
        .select('id')
        .single()

      if (roomErr) {
        console.error('Supabase Error creating room:', roomErr)
        throw roomErr
      }

      // 2. Add creator as owner
      const { error: memberErr } = await supabase
        .from('room_members')
        .insert({ room_id: room.id, user_id: userId, role: 'owner' })

      if (memberErr) {
        console.error('Supabase Error adding creator to room members:', memberErr)
        throw memberErr
      }

      // 3. Activity log
      const { error: logErr } = await supabase.from('activity_log').insert({
        room_id: room.id,
        user_id: userId,
        action: 'room_created',
      })

      if (logErr) {
        console.error('Supabase Error logging activity:', logErr)
        // Don't throw for log errors as the room is already created successfully
      }

      onOpenChange(false)
      ;(e.target as HTMLFormElement).reset()
      onSuccess()
    } catch (err: any) {
      console.error('Error in handleSubmit:', err)
      const msg = err.message || 'Failed to create room'
      setError(msg)
      toast.error(msg)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-[#ffffff] border border-[#e7e7e7] text-[#141414] sm:max-w-md rounded-[16px] shadow-none p-6 font-sans">
        <DialogHeader className="space-y-3">
          <div className="flex items-center gap-3 mb-1">
            <div className="w-8 h-8 rounded-[5px] border border-[#e7e7e7] flex items-center justify-center bg-[#f4eee5]">
              <BookOpen className="w-4 h-4 text-[#141414]" />
            </div>
            <DialogTitle className="text-[#141414] text-heading-sm font-semibold tracking-tight">
              Create Study Room
            </DialogTitle>
          </div>
          <DialogDescription className="text-[#4e4d4c] text-[13px] tracking-normal font-normal">
            An 8-character invite code will be auto-generated for your room.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 mt-3">
          {error && (
            <div className="rounded-[5px] bg-[#f4eee5] border border-[#cc3737]/20 px-3.5 py-2.5 text-[13px] font-normal text-[#cc3737]">
              {error}
            </div>
          )}

          <div className="space-y-1.5">
            <Label htmlFor="create-name" className="text-[#4e4d4c] text-[13px] font-medium tracking-normal flex items-center justify-between">
              <span>Room Name <span className="text-[#cc3737]">*</span></span>
            </Label>
            <Input
              id="create-name"
              name="name"
              placeholder="e.g. UPSC 2025 PREP"
              maxLength={50}
              required
              disabled={loading}
              className="bg-white border border-[#e7e7e7] text-[#141414] placeholder:text-[#a1a1a1] focus-visible:ring-1 focus-visible:ring-[#0A7C6E] focus-visible:border-[#141414] rounded-[5px] text-[14px] h-10 font-normal"
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="create-subject" className="text-[#4e4d4c] text-[13px] font-medium tracking-normal">
              Subject / Topic <span className="text-[#cc3737]">*</span>
            </Label>
            <Input
              id="create-subject"
              name="subject"
              placeholder="e.g. MATHEMATICS, DSA, CHEMISTRY"
              required
              disabled={loading}
              className="bg-white border border-[#e7e7e7] text-[#141414] placeholder:text-[#a1a1a1] focus-visible:ring-1 focus-visible:ring-[#0A7C6E] focus-visible:border-[#141414] rounded-[5px] text-[14px] h-10 font-normal"
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="create-description" className="text-[#4e4d4c] text-[13px] font-medium tracking-normal">
              Description <span className="text-[#737373] font-normal">(optional, max 200 chars)</span>
            </Label>
            <Textarea
              id="create-description"
              name="description"
              placeholder="What topics will you cover in this room?"
              maxLength={200}
              rows={3}
              disabled={loading}
              className="bg-white border border-[#e7e7e7] text-[#141414] placeholder:text-[#a1a1a1] focus-visible:ring-1 focus-visible:ring-[#0A7C6E] focus-visible:border-[#141414] rounded-[5px] text-[14px] font-normal resize-none p-3"
            />
          </div>

          <div className="flex justify-end gap-3 pt-4 border-t border-[#e7e7e7] mt-6">
            <Button
              type="button"
              onClick={() => onOpenChange(false)}
              disabled={loading}
              className="bg-transparent text-[#4e4d4c] hover:text-[#141414] hover:bg-[#f4eee5] rounded-[5px] font-medium text-[14px] px-4 h-10 transition-all border-none shadow-none cursor-pointer"
            >
              Cancel
            </Button>
            <Button
              id="create-room-submit"
              type="submit"
              disabled={loading}
              className="btn-evernote-primary h-10 min-w-28 text-[14px]"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin text-white" />
                  Creating…
                </>
              ) : (
                'Create Room'
              )}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}

